### ISSUE TITLE
Docker run sample document support

### ISSUE THREAD

**Issue by yl-yue** [wzshiming/bridge#1]
Docker运行示例文档支持

Docker run sample document support

**Comment by wzshiming** [comment]
如果要使用 docker 直接吧 `bridge` 换成 `docker run --rm -it wzshiming/bridge`
如 `bridge -b :8080 -p github.io:80 -p ssh://username:password@my_server:22` 
换成 `docker run --rm -p 8080:8080 -it wzshiming/bridge bridge -b :8080 -p github.io:80 -p ssh://username:password@my_server:22`

**Comment by yl-yue** [comment]
> 如果要使用 docker 直接吧 `bridge` 换成 `docker run --rm -it wzshiming/bridge`
> 如 `bridge -b :8080 -p github.io:80 -p ssh://username:password@my_server:22`
> 换成 `docker run --rm -p 8080:8080 -it wzshiming/bridge -b :8080 -p github.io:80 -p ssh://username:password@my_server:22`

好的，感谢提供思路！
