### ISSUE TITLE
How to reuse upstream proxy connections?

### ISSUE THREAD

**Issue by Le0Developer** [wzshiming/bridge#18]
Is it possible to reuse the same connection to the upstream proxy?

Currently I am doing `bridge -b http://127.0.0.1:3000 -p - -p http://127.0.0.1:8080` and then connect multiple clients to `http://127.0.0.1:3000`. This opens multiple connections to `http://127.0.0.1:8080` which I don't want.
I want a single connection to the upstream proxy.

**Comment by wzshiming** [comment]
HTTP proxy protocol does not support reuse connections, you can try ssh which does.

**Comment by Le0Developer** [comment]
Unfortunately I don't have control over the upstream proxy and they don't provide anything but HTTP for proxying.
It's some really weird and ancient corporate proxy with access control that only allows one concurrent connection and ratelimits new connections, so you need to reuse or it won't work.

**Comment by Le0Developer** [comment]
It's HTTPS request, so it's a TLS stream.

**Comment by wzshiming** [comment]
It doesn't work. The protocol specifies that a connection can only be made once to a single destination.

If the destination is ssh to the server, I can make it reusable. If it's https, I'll just have to rely on h2c's reuse capabilities (which it doesn't seem to have), and if it's a different server, it won't work.

**Comment by Le0Developer** [comment]
Thanks, I will need to find a different solution to my problem.
I'm not too deep in on the technicalities, but would a socks(4/5) proxy provide such reuse aswell?

**Comment by wzshiming** [comment]
No, they are the same as http proxy. ssh proxy is the only general proxy that supports reuse.

**Comment by Le0Developer** [comment]
Unfortunate, thanks for your help.
