### ISSUE TITLE
Update `go get` to `go install`.

### ISSUE THREAD

**Issue by hongyi-zhao** [wzshiming/bridge#20]
As documented [here](https://go.dev/doc/go-get-install-deprecation), [the installation method](https://github.com/wzshiming/bridge?tab=readme-ov-file#install) should be updated to the following:

```shell
werner@x13dai-t:~$ go install github.com/wzshiming/bridge/cmd/bridge@latest
werner@x13dai-t:~$ ls $GOPATH/bin -la
total 12544
drwxrwxr-x 2 werner werner     4096  7月 17 14:18 .
drwxrwxr-x 4 werner werner     4096  7月 16 13:16 ..
-rwxrwxr-x 1 werner werner 12835337  7月 17 14:18 bridge
```

**Comment by wzshiming** [comment]
Ah, that sounds good to me, the README has not been maintained for a long time

**Comment by wzshiming** [comment]
Fixed by https://github.com/wzshiming/bridge/pull/24
