### ISSUE TITLE
Establishing a Secure Reverse Proxy with Bridge for Accessing Internal Networks from the Public Internet.

### ISSUE THREAD

**Issue by hongyi-zhao** [wzshiming/bridge#22]
I'm trying to figure out a method to securely access resources on an internal network from the public internet using the bridge tool. The setup involves three main components:

- An internal machine within the private network.
- A publicly accessible server with a known public IP address.
- A client machine on the public internet seeking access to internal resources.

The process works as follows:

The internal machine initiates a connection to the public server using bridge, establishing a reverse SSH tunnel:

`bridge -b :0 -p ssh://public_ip:12022`
 

The public server runs bridge to listen for SSH connections and forward them to a SOCKS5 proxy:

`bridge -b socks5://:1080 -p ssh://:12022`

Clients can then access internal network resources through the SOCKS5 proxy on the public server:

`curl -x socks5://public_ip:1080 http://internal_service_address`

 
Am I right?

Regards,
Zhao

**Comment by wzshiming** [comment]
I guess the following command run on your internal machine will meet your needs.

I recommend using the ssh key to access the server will be safer.

```
bridge \
  -b socks5://:1080 \
  -b ssh://user@public_ip:22?identity_file=/root/.ssh/id_rsa \
  -p -
```

**Comment by hongyi-zhao** [comment]
Then, you suggest the following steps?

- On the internal machine:

```
bridge \
  -b socks5://:1080 \
  -b ssh://root@public_ip:22?identity_file=/root/.ssh/id_rsa \
  -p -
```
- On the public server:

`bridge -b socks5://:1080 -p ssh://:22`

- Use it as follows:

`curl -x socks5://public_ip:1080 http://internal_service_address`

**Comment by wzshiming** [comment]
The public server does nothing, just add the pub key of the internal machine to `/root/.ssh/authorized_keys` of it.

**Comment by hongyi-zhao** [comment]
By saying **The public server does nothing**, do you mean the following step can be omitted?

> * On the public server:
> 
> 
> `bridge -b socks5://:1080 -p ssh://:22`

**Comment by wzshiming** [comment]
Yep

**Comment by hongyi-zhao** [comment]
Are the following two methods roughly equivalent?
- The method discussed here:
```
bridge \
  -b socks5://:1080 \
  -b ssh://root@public_ip:22?identity_file=/root/.ssh/id_rsa \
  -p -
```
- Pure ssh based method:
`ssh public_ip -R 50000:localhost:22 "ssh -D 1080 localhost -p 50000"`

**Comment by wzshiming** [comment]
Yep, you can do it in any of the 3 ways.

The bridge was originally designed with the need to pass through multiple jump machines.
e.g.

```bash
bridge \
  -b socks5://:1080 \
  -b ssh://root@internal_ip_2:22?identity_file=/root/.ssh/id_rsa \
  -b ssh://root@internal_ip_1:22?identity_file=/root/.ssh/id_rsa \
  -b ssh://root@public_ip:22?identity_file=/root/.ssh/id_rsa \
  -p -
```
It listened to internal_ip_2 1080 via 3 machines

**Comment by hongyi-zhao** [comment]
Let me try to give alternative pure ssh-based counterparts to the above bridge method:

1. Using `ProxyJump (-J)` for simplicity: 
```
ssh -J root@public_ip:22,root@internal_ip_1:22,root@internal_ip_2:22 \
     -i /root/.ssh/id_rsa \
     -fNT -R 1080:localhost \
     root@other_public_ip_1:22 \
     root@other_public_ip_2:22
```
2. Using `ProxyCommand` for more granular controls:

```
ssh -o "ProxyCommand ssh -W %h:%p root@public_ip -i /root/.ssh/id_rsa" \
    -o "ProxyCommand ssh -W %h:%p root@internal_ip_1 -i /root/.ssh/id_rsa" \
    -o "ProxyCommand ssh -W %h:%p root@internal_ip_2 -i /root/.ssh/id_rsa" \
    -i /root/.ssh/id_rsa \
    -fNT -R 1080:localhost \
    root@other_public_ip_1 \
    root@other_public_ip_2
```

**Comment by wzshiming** [comment]
Actually, I can't remember the command of ssh or other proxy tools

**Comment by hongyi-zhao** [comment]
It is certain that even if they can be implemented, there will be numerous pitfalls and extreme complications.

**Comment by hongyi-zhao** [comment]
Another wonderful tool is [gost](https://github.com/go-gost/gost).

**Comment by wzshiming** [comment]
It is not the same as Bridge's goal, which leads to the difference in functionality, it can not be implemented to listen to the remote server's port, and as a parameter to the ssh ProxyCommand.
