### ISSUE TITLE
用本地端口监听 报 Cannot open file "socks5://127.0.0.1:8080"

### ISSUE THREAD

**Issue by WangJarvis** [wzshiming/bridge#27]
我想在本地监听一个socks端口 然后转发到远程socks5，这条命令 报 Cannot open file "socks5://[127.0.0.1:8080](https://127.0.0.1:8080/)" for reading: No such file or directory，使用命令如下:
bridge -b socks5://127.0.0.1:8080  -p socks5://user-xxx:xxxxx@968ac0a9a609c7b1.xx.na.xx.vip:4600
报错信息：
Cannot open file "socks5://127.0.0.1:8080" for reading: No such file or directory
是不是我用法问题

![3](https://github.com/user-attachments/assets/2b8020b2-d1f0-40d9-8038-c7ced0b11161)
![b2](https://github.com/user-attachments/assets/3d5ec4c5-6443-473f-a7c7-f2c3ad70de22)
![bige](https://github.com/user-attachments/assets/b27d280e-367c-44d9-ae6c-e8c209696389)

**Comment by wzshiming** [comment]
这样用, 少了一个 `-p -`
```
bridge -b socks5://127.0.0.1:8080 -p - -p socks5://user-xxx:xxxxx@968ac0a9a609c7b1.xx.na.xx.vip:4600
```

**Comment by WangJarvis** [comment]
这种提示 是对的吗 我一开始也是这么用的

**Comment by WangJarvis** [comment]
![Uploading 4.png…]()

**Comment by WangJarvis** [comment]
bridge -b socks5://127.0.0.1:8080 -p - -p socks5://user-xxx:xxxxx@968ac0a9a609c7b1.xx.na.xx.vip:4600
报：                    Usage: bridge [ OPTIONS ] OBJECT { COMMAND | help }                                                        bridge [ -force ] -batch filename
where  OBJECT := { link | fdb | mdb | mst | vlan | vni | monitor }                                         OPTIONS := { -V[ersion] | -s[tatistics] | -d[etails] |
                    -o[neline] | -t[imestamp] | -n[etns] name |
                    -com[pressvlans] -c[olor] -p[retty] -j[son] }
~ $

**Comment by WangJarvis** [comment]
![4](https://github.com/user-attachments/assets/658bc0c2-b481-40f2-8b8e-e8f506c90772)

**Comment by WangJarvis** [comment]
$ bridge -V
bridge utility, 6.12.0   这是我用的版本

**Comment by wzshiming** [comment]
... 你用错了 你用的是另一个同名的工具 当前这个你需要自己安装的

**Comment by WangJarvis** [comment]
$ go install github.com/wzshiming/bridge/cmd/bridge@latest   我是看文档用这个命令安装的 现在是不用了吗

**Comment by wzshiming** [comment]
安装之后是在~/go/bin 目录下, 你没有将其加入 $PATH

**Comment by wzshiming** [comment]
`~/go/bin/bridge -b socks5://127.0.0.1:8080 -p - -p socks5://user-xxx:xxxxx@968ac0a9a609c7b1.xx.na.xx.vip:4600`

**Comment by WangJarvis** [comment]
十分感谢哈，已经可以了。 我遇到另外一个问题，还麻烦帮忙解答一下，我开了新的issues: [https://github.com/wzshiming/bridge/issues/28](url)
