### ISSUE TITLE
Multiple platform support via Appimage ?

### ISSUE THREAD

**Issue by Docop2** [wzshiming/bridge#4]
Hi
 So the setup and usage look quite easy. I do wonder, has having multiple package.. perhaps having a .appimage can be helpfull ? Also, that will make possible to run it in Centos 7.
thanks , great project.

**Comment by wzshiming** [comment]
Hi @Docop2 
Good suggestion, I will take the time to look at AppImage later, 
but if you want to run on CentOS7, you can download the compiled binary file directly. It is statically linked and is compatible in most cases.

https://github.com/wzshiming/bridge/releases/tag/v0.5.0
