### ISSUE TITLE
Assigning multiple proxies for a rule

### ISSUE THREAD

**Issue by DefiDebauchery** [wzshiming/bridge#5]
Thanks for the useful program, this is very cool!

Is it possible to configure multiple proxies for a route? Maybe something like
`bridge -b :8080 -p - -p socks5://server1:1080,socks5://server2:1080,socks5://server3:1080` 
where it would be either random or round-robin.

There are actually several use-cases I could see here, from geo-based endpoint monitoring to load-balancing when using multi-slot downloaders like [axel](https://github.com/axel-download-accelerator/axel/).

**Comment by wzshiming** [comment]
This already has a round-robin, use '|' instead of ','
`bridge -b :8080 -p - -p 'socks5://server1:1080|socks5://server2:1080|socks5://server3:1080' `

**Comment by DefiDebauchery** [comment]
Greatly appreciated, thank you for the response!
